// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Generated by scripts/upstream-resource-modules.mjs from upstream/libapps.
// Do not edit this file directly.

export const gitDate = "2026-06-16T00:07:07-07:00";
export const version = "9.0.0";
